from torchsense.metrics.losses import negative_si_snr,ScaleInvariantSignalNoiseRatio
from torchsense.metrics.triplet import SoftTripletLoss,TripletLoss,SoftTripletLoss
from torchsense.metrics.mape import mape_loss